# AgriMarket

## 농수산물


- Data Source : [농식품 빅데이터 거래소](https://kadx.co.kr/product/detail/94534d90-595d-11eb-acdd-9560621d9652)

- Collection Method : Download

- Data Format : CSV

### 데이터 설명

- 일반농산물 도매 69품목 116품종, 소매 90품목 143품종 및 친환경농산물 38품목 44종 대상 가격 자료


## 소비자 물가지수 


- Data Source : [국가통계포털](https://kosis.kr/statHtml/statHtml.do?orgId=101&tblId=DT_1J20112&conn_path=I2)

- Collection Method : Download

- Data Format : CSV

### 데이터 설명

- 농산물 중 필수재라고 판단되는 곡물,채소 포함

- 사치재인 과실, 기타 농산물 제외

In [35]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import koreanize_matplotlib
%config InlineBackend.figure_format = 'retina'

root_path = "../"
data_path = f"{root_path}data"

col_detail={
'prce_reg_ymd' : '가격등록일자',
'mrkt_esnt_no' : '시장고유번호',
'mrkt_code' : '시장코드',
'mrkt_nm' : '시장명',
'ct_code' : '시도코드',
'ctnp_nm' : '시도명',
'sggu_code' : '시군구코드',
'sggu_nm' : '시군구명',
'pdlt_code' : '품목코드',
'pdlt_nm' : '품목명',
'spcs_code' : '품종코드',
'spcs_nm' : '품종명',
'wsrt_exmn_se_code' : '도소매조사구분코드',
'exmn_se_nm' : '조사구분명',
'bulk_grad_code' : '산물등급코드',
'bulk_grad_nm' : '산물등급명',
'pdlt_prce' : '품목가격',
'mtc_smt_unit_mg' : '산지출하단위크기',
'mtc_smt_unit_nm' : '산지출하단위명',
'whsl_smt_unit_mg' : '도매출하단위크기',
'whsl_smt_unit_nm' : '도매출하단위명',
'rtsl_smt_unit_mg' : '소매출하단위크기',
'rtsl_smt_unit_nm' : '소매출하단위명',
'evfd_fmpd_smt_unit_mg' : '친환경농산물출하단위크기',
'evfd_fmpd_smt_unit_nm' : '친환경농산물출하단위명',
'dcnt_prce_yn' : '할인가격여부',
'etl_ldg_dt' : 'ETL적재일시'
}

# 파일 호출, 변수명 및 불러오기 경로는 자신에게 맞게 변경해주시면 됩니다.

In [36]:
import os
files_path = f'{data_path}/TB_TAT_KAMIS_PRC_MK_TB/'
files = os.listdir(files_path)
files.remove('.DS_Store')
print(files)

['TB_TAT_KAMIS_PRC_MK_TB-2019.csv', 'TB_TAT_KAMIS_PRC_MK_TB-2018.csv', 'TB_TAT_KAMIS_PRC_MK_TB-2008.csv', 'TB_TAT_KAMIS_PRC_MK_TB-2020.csv', 'TB_TAT_KAMIS_PRC_MK_TB-2009.csv', 'TB_TAT_KAMIS_PRC_MK_TB-2010.csv', 'TB_TAT_KAMIS_PRC_MK_TB-2011.csv', 'TB_TAT_KAMIS_PRC_MK_TB-2005.csv', 'TB_TAT_KAMIS_PRC_MK_TB-2013.csv', 'TB_TAT_KAMIS_PRC_MK_TB-2007.csv', 'TB_TAT_KAMIS_PRC_MK_TB-2006.csv', 'TB_TAT_KAMIS_PRC_MK_TB-2012.csv', 'TB_TAT_KAMIS_PRC_MK_TB-2016.csv', 'TB_TAT_KAMIS_PRC_MK_TB-2017.csv', 'TB_TAT_KAMIS_PRC_MK_TB-2015.csv', 'TB_TAT_KAMIS_PRC_MK_TB-2014.csv']

In [37]:
df = pd.DataFrame()
for file in files:
    df_sub = pd.read_csv(f'{files_path}/{file}', encoding='cp949', low_memory=False)
    df_sub = df_sub[['PRCE_REG_YMD', 'CTNP_NM', 'PDLT_NM', 'EXMN_SE_NM', 'BULK_GRAD_NM', 'PDLT_PRCE']]
    df_sub = df_sub[~df_sub['PDLT_NM'].isna()]
    df_sub.columns=['YMD', 'Region', 'Product', 'WR', 'Grade', 'Price']
    df = pd.concat([df, df_sub])

# 1. 년·월·일 에서 연·월 로 변경
# 2. Y(년), M(월) 컬럼 생성

In [82]:
df['YMD'] = df['YMD'].astype(str)

df['Y'] = df['YMD'].map(lambda x:x[:4]).astype('int16')
df['M'] = df['YMD'].map(lambda x:x[4:6]).astype('int8')
df['D'] = df['YMD'].map(lambda x:x[6:]).astype('int8')
df['YM'] = df['YMD'].map(lambda x:x[:6]).astype('int32')

In [83]:
# 20년 데이터만 있는 품목 제외

df = df[~df['Product'].isin(['즉석밥', '두부', '김치', '고추장', '된장', '간장', '맛김(조미김)', '콩나물'])]

In [84]:
df.loc[df["Product"]=="피마늘", "Product"] = "마늘"

In [85]:
# Wholesale : 도매
df_w = df[df['WR']=='도매']

In [86]:
# Retail : 소매
df_r = df[df['WR']=='소매']

In [87]:
product_w = df_w['Product'].unique()
product_w = product_w.tolist()

In [88]:
product_r = df_r['Product'].unique()
product_r = product_r.tolist()

In [89]:
df

              YMD Region Product  WR Grade    Price     Y   M   D      YM
0        20190102     서울      단감  도매    상품  33000.0  2019   1   2  201901
1        20190102     서울      단감  도매    중품  28000.0  2019   1   2  201901
2        20190102     서울     바나나  도매    상품  22000.0  2019   1   2  201901
3        20190102     서울     바나나  도매    중품  17000.0  2019   1   2  201901
4        20190102     서울     참다래  도매    상품  35000.0  2019   1   2  201901
...           ...    ...     ...  ..   ...      ...   ...  ..  ..     ...
1014738  20141231     강원      참깨  소매    중품   2980.0  2014  12  31  201412
1014739  20141231     충북      참깨  소매    중품   3240.0  2014  12  31  201412
1014740  20141231     전북      참깨  소매    중품   3000.0  2014  12  31  201412
1014741  20141231     경남      참깨  소매    중품   3500.0  2014  12  31  201412
1014742  20141231     제주      참깨  소매    중품   2500.0  2014  12  31  201412

[14237910 rows x 10 columns]

# 물가지수 파일과 겹치는 품목 확인

In [90]:
df_1 = pd.read_csv(f'{data_path}/소비자물가지수_품목별_연도별_월별_filtered.csv')

In [91]:
df_1['품목별'].unique()

array(['총지수', '농축수산물', '\u3000\u3000\u3000(농산물)곡물',
       '\u3000\u3000\u3000\u3000\u3000\u3000쌀',
       '\u3000\u3000\u3000\u3000\u3000\u3000현미',
       '\u3000\u3000\u3000\u3000\u3000\u3000찹쌀',
       '\u3000\u3000\u3000\u3000\u3000\u3000보리쌀',
       '\u3000\u3000\u3000\u3000\u3000\u3000콩',
       '\u3000\u3000\u3000\u3000\u3000\u3000땅콩',
       '\u3000\u3000\u3000\u3000\u3000\u3000혼식곡',
       '\u3000\u3000\u3000(농산물)채소',
       '\u3000\u3000\u3000\u3000\u3000\u3000배추',
       '\u3000\u3000\u3000\u3000\u3000\u3000상추',
       '\u3000\u3000\u3000\u3000\u3000\u3000시금치',
       '\u3000\u3000\u3000\u3000\u3000\u3000양배추',
       '\u3000\u3000\u3000\u3000\u3000\u3000미나리',
       '\u3000\u3000\u3000\u3000\u3000\u3000깻잎',
       '\u3000\u3000\u3000\u3000\u3000\u3000부추',
       '\u3000\u3000\u3000\u3000\u3000\u3000무',
       '\u3000\u3000\u3000\u3000\u3000\u3000열무',
       '\u3000\u3000\u3000\u3000\u3000\u3000당근',
       '\u3000\u3000\u3000\u3000\u3000\u3000감자',
       '\u3000\u3000\u3000\u3000\u3000\u3000고구마',
       '\u3000\u3000\u3000\u3000\u3000\u3000도라지',
       '\u3000\u3000\u3000\u3000\u3000\u3000콩나물',
       '\u3000\u3000\u3000\u3000\u3000\u3000버섯',
       '\u3000\u3000\u3000\u3000\u3000\u3000오이',
       '\u3000\u3000\u3000\u3000\u3000\u3000풋고추',
       '\u3000\u3000\u3000\u3000\u3000\u3000호박',
       '\u3000\u3000\u3000\u3000\u3000\u3000가지',
       '\u3000\u3000\u3000\u3000\u3000\u3000토마토',
       '\u3000\u3000\u3000\u3000\u3000\u3000파',
       '\u3000\u3000\u3000\u3000\u3000\u3000양파',
       '\u3000\u3000\u3000\u3000\u3000\u3000마늘',
       '\u3000\u3000\u3000\u3000\u3000\u3000브로콜리',
       '\u3000\u3000\u3000\u3000\u3000\u3000고사리',
       '\u3000\u3000\u3000\u3000\u3000\u3000파프리카',
       '\u3000\u3000\u3000\u3000\u3000\u3000생강',
       '\u3000\u3000\u3000(농산물)과실',
       '\u3000\u3000\u3000\u3000\u3000\u3000사과',
       '\u3000\u3000\u3000\u3000\u3000\u3000배',
       '\u3000\u3000\u3000\u3000\u3000\u3000복숭아',
       '\u3000\u3000\u3000\u3000\u3000\u3000포도',
       '\u3000\u3000\u3000\u3000\u3000\u3000밤',
       '\u3000\u3000\u3000\u3000\u3000\u3000감',
       '\u3000\u3000\u3000\u3000\u3000\u3000귤',
       '\u3000\u3000\u3000\u3000\u3000\u3000오렌지',
       '\u3000\u3000\u3000\u3000\u3000\u3000참외',
       '\u3000\u3000\u3000\u3000\u3000\u3000수박',
       '\u3000\u3000\u3000\u3000\u3000\u3000딸기',
       '\u3000\u3000\u3000\u3000\u3000\u3000바나나',
       '\u3000\u3000\u3000\u3000\u3000\u3000키위'], dtype=object)

In [92]:
# replace로 \u3000 값이 사라지지 않는다.. 이유는 모르겠음
df_1['품목별'] = df_1['품목별'].replace('\u3000', '')

In [93]:
df_1['품목별'] = df_1['품목별'].map(lambda x:x.strip(('\u3000')))

In [94]:
df['Product'].unique()

array(['단감', '바나나', '참다래', '파인애플', '오렌지', '방울토마토', '고등어', '갈치', '명태',
       '물오징어', '건멸치', '북어', '건오징어', '김', '건미역', '굴', '고구마', '감자', '배추',
       '양배추', '시금치', '상추', '얼갈이배추', '수박', '오이', '호박', '토마토', '딸기', '무',
       '당근', '열무', '건고추', '풋고추', '붉은고추', '마늘', '양파', '파', '생강', '미나리',
       '깻잎', '피망', '파프리카', '멜론', '느타리버섯', '팽이버섯', '새송이버섯', '사과', '배',
       '레몬', '망고', '전복', '새우', '깐마늘(국산)', '감귤', '포도', '쌀', '찹쌀', '콩', '팥',
       '녹두', '메밀', '참깨', '들깨', '땅콩', '쇠고기', '돼지고기', '닭고기', '계란', '수입조기',
       '호두', '아몬드', '건포도', '건블루베리', '고춧가루', '멸치액젓', '갓', '새우젓', '굵은소금',
       '꽁치', '우유', '부추', '참외', '체리', '복숭아', '가지', '자몽', '깐마늘(수입)', '브로콜리',
       '청경채', '케일', '양송이버섯', '표고버섯', '귀리', '보리', '수수', '율무', '양상추', '혼합곡'],
      dtype=object)

# 농수산물 데이터와 주요경제지표 합치기

In [95]:
file = f"{data_path}/주요경제지표_20052021.xlsx"
df_mei = pd.read_excel(file, engine="openpyxl")
print(df_mei.shape)
display(df_mei.head(df_mei.shape[0]))

(17, 11)

/opt/anaconda3/lib/python3.9/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,연도,생산자물가지수(2010=100),소비자물가지수(2015=100),경상수지(백만US$),자본수지(백만US$),외환보유액(백만US$),수출액(백만US$),수입액(백만US$),환율(원/US$),실업률(%),콜금리(연%)
0,2021,110.64,108.050,88302.7,-154.3,463118.360,644400.370,615093.450,1144.42,3.7,0.61
1,2020,104.01,105.420,75275.7,-386.3,443098.120,512788.730,467548.715,1180.05,3.9,0.70
2,2019,104.48,104.850,59670.1,-169.3,408816.146,542232.610,503342.947,1157.80,3.8,1.59
3,2018,104.46,104.450,76408.5,316.7,403694.264,604859.657,535202.428,1118.10,3.8,1.52
4,2017,102.53,102.930,78460.0,-26.8,389266.683,573694.421,478478.296,1071.40,3.7,1.26
5,2016,99.11,100.970,98677.4,-46.2,371101.605,495425.934,406192.887,1208.50,3.7,1.34
6,2015,100.95,100.000,105939.6,-60.2,367961.865,526756.498,436498.973,1172.00,3.6,1.65
7,2014,105.17,99.298,84374.0,-8.9,363592.748,572664.602,525514.506,1099.20,3.5,2.34
8,2013,105.73,98.048,81148.2,-27.0,346459.569,559632.400,515585.500,1055.30,3.1,2.59
9,2012,107.45,96.789,50835.0,-41.7,326968.393,547869.800,519584.500,1071.10,3.2,3.08
10,2011,106.71,94.717,18655.8,-112.0,306402.488,555213.700,524413.100,1153.30,3.4,3.09
11,2010,100.00,91.051,28850.4,-63.2,291570.661,466383.762,425212.160,1138.90,3.7,2.16
12,2009,96.33,88.452,33593.3,-69.6,269994.736,363533.400,323084.400,1167.60,3.6,1.98
13,2008,96.53,86.079,3189.7,26.4,201223.413,422007.300,435274.700,1257.50,3.2,4.78
14,2007,88.93,82.235,11794.5,5.7,262224.070,371489.000,356845.800,938.20,3.2,4.77
15,2006,87.67,80.202,3569.2,-69.0,238956.116,325464.849,309382.632,929.60,3.5,4.19
16,2005,86.88,78.444,12654.8,-0.6,210390.703,284418.700,261238.300,1013.00,3.7,3.33

In [96]:
df_mei = df_mei[df_mei["연도"] <= 2020]

In [97]:
df_mei = df_mei.rename(columns={"연도" : "Y"})
df_mei

,Y,생산자물가지수(2010=100),소비자물가지수(2015=100),경상수지(백만US$),자본수지(백만US$),외환보유액(백만US$),수출액(백만US$),수입액(백만US$),환율(원/US$),실업률(%),콜금리(연%)
1,2020,104.01,105.420,75275.7,-386.3,443098.120,512788.730,467548.715,1180.05,3.9,0.70
2,2019,104.48,104.850,59670.1,-169.3,408816.146,542232.610,503342.947,1157.80,3.8,1.59
3,2018,104.46,104.450,76408.5,316.7,403694.264,604859.657,535202.428,1118.10,3.8,1.52
4,2017,102.53,102.930,78460.0,-26.8,389266.683,573694.421,478478.296,1071.40,3.7,1.26
5,2016,99.11,100.970,98677.4,-46.2,371101.605,495425.934,406192.887,1208.50,3.7,1.34
6,2015,100.95,100.000,105939.6,-60.2,367961.865,526756.498,436498.973,1172.00,3.6,1.65
7,2014,105.17,99.298,84374.0,-8.9,363592.748,572664.602,525514.506,1099.20,3.5,2.34
8,2013,105.73,98.048,81148.2,-27.0,346459.569,559632.400,515585.500,1055.30,3.1,2.59
9,2012,107.45,96.789,50835.0,-41.7,326968.393,547869.800,519584.500,1071.10,3.2,3.08
10,2011,106.71,94.717,18655.8,-112.0,306402.488,555213.700,524413.100,1153.30,3.4,3.09
11,2010,100.00,91.051,28850.4,-63.2,291570.661,466383.762,425212.160,1138.90,3.7,2.16
12,2009,96.33,88.452,33593.3,-69.6,269994.736,363533.400,323084.400,1167.60,3.6,1.98
13,2008,96.53,86.079,3189.7,26.4,201223.413,422007.300,435274.700,1257.50,3.2,4.78
14,2007,88.93,82.235,11794.5,5.7,262224.070,371489.000,356845.800,938.20,3.2,4.77
15,2006,87.67,80.202,3569.2,-69.0,238956.116,325464.849,309382.632,929.60,3.5,4.19
16,2005,86.88,78.444,12654.8,-0.6,210390.703,284418.700,261238.300,1013.00,3.7,3.33

In [220]:
df_market = pd.merge(df, df_mei)
df_market

,YMD,Region,Product,WR,Grade,Price,Y,M,D,YM,생산자물가지수(2010=100),소비자물가지수(2015=100),경상수지(백만US$),자본수지(백만US$),외환보유액(백만US$),수출액(백만US$),수입액(백만US$),환율(원/US$),실업률(%),콜금리(연%)
0,20190102,서울,단감,도매,상품,33000.0,2019,1,2,201901,104.48,104.850,59670.1,-169.3,408816.146,542232.610,503342.947,1157.8,3.8,1.59
1,20190102,서울,단감,도매,중품,28000.0,2019,1,2,201901,104.48,104.850,59670.1,-169.3,408816.146,542232.610,503342.947,1157.8,3.8,1.59
2,20190102,서울,바나나,도매,상품,22000.0,2019,1,2,201901,104.48,104.850,59670.1,-169.3,408816.146,542232.610,503342.947,1157.8,3.8,1.59
3,20190102,서울,바나나,도매,중품,17000.0,2019,1,2,201901,104.48,104.850,59670.1,-169.3,408816.146,542232.610,503342.947,1157.8,3.8,1.59
4,20190102,서울,참다래,도매,상품,35000.0,2019,1,2,201901,104.48,104.850,59670.1,-169.3,408816.146,542232.610,503342.947,1157.8,3.8,1.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14237905,20141231,강원,참깨,소매,중품,2980.0,2014,12,31,201412,105.17,99.298,84374.0,-8.9,363592.748,572664.602,525514.506,1099.2,3.5,2.34
14237906,20141231,충북,참깨,소매,중품,3240.0,2014,12,31,201412,105.17,99.298,84374.0,-8.9,363592.748,572664.602,525514.506,1099.2,3.5,2.34
14237907,20141231,전북,참깨,소매,중품,3000.0,2014,12,31,201412,105.17,99.298,84374.0,-8.9,363592.748,572664.602,525514.506,1099.2,3.5,2.34
14237908,20141231,경남,참깨,소매,중품,3500.0,2014,12,31,201412,105.17,99.298,84374.0,-8.9,363592.748,572664.602,525514.506,1099.2,3.5,2.34
14237909,20141231,제주,참깨,소매,중품,2500.0,2014,12,31,201412,105.17,99.298,84374.0,-8.9,363592.748,572664.602,525514.506,1099.2,3.5,2.34

In [221]:
crop_list = [
    "호박",
    "고구마",
    "양파",
    "무",
    "배",
    "배추",
    "마늘",
    "양배추",
    "시금치",
    "콩",
    "땅콩",
    "풋고추",
    "오이",
    "깻잎",
    "생강",
    "사과",
    "포도",
    "당근",
    "복숭아",
    "미나리",
    "감자",
    "열무",
    "쌀",
]

len(crop_list)

23

In [222]:
df_market = df_market[df_market["Product"].isin(crop_list)]
df_market

,YMD,Region,Product,WR,Grade,Price,Y,M,D,YM,생산자물가지수(2010=100),소비자물가지수(2015=100),경상수지(백만US$),자본수지(백만US$),외환보유액(백만US$),수출액(백만US$),수입액(백만US$),환율(원/US$),실업률(%),콜금리(연%)
27,20190102,서울,고구마,도매,상품,41000.0,2019,1,2,201901,104.48,104.850,59670.1,-169.3,408816.146,542232.610,503342.947,1157.8,3.8,1.59
28,20190102,서울,고구마,도매,중품,36000.0,2019,1,2,201901,104.48,104.850,59670.1,-169.3,408816.146,542232.610,503342.947,1157.8,3.8,1.59
29,20190102,서울,감자,도매,상품,46000.0,2019,1,2,201901,104.48,104.850,59670.1,-169.3,408816.146,542232.610,503342.947,1157.8,3.8,1.59
30,20190102,서울,감자,도매,중품,36000.0,2019,1,2,201901,104.48,104.850,59670.1,-169.3,408816.146,542232.610,503342.947,1157.8,3.8,1.59
31,20190102,서울,감자,도매,상품,50000.0,2019,1,2,201901,104.48,104.850,59670.1,-169.3,408816.146,542232.610,503342.947,1157.8,3.8,1.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14237679,20141231,서울,배,도매,중품,30000.0,2014,12,31,201412,105.17,99.298,84374.0,-8.9,363592.748,572664.602,525514.506,1099.2,3.5,2.34
14237680,20141231,부산,배,도매,중품,30000.0,2014,12,31,201412,105.17,99.298,84374.0,-8.9,363592.748,572664.602,525514.506,1099.2,3.5,2.34
14237681,20141231,대구,배,도매,중품,26000.0,2014,12,31,201412,105.17,99.298,84374.0,-8.9,363592.748,572664.602,525514.506,1099.2,3.5,2.34
14237682,20141231,광주,배,도매,중품,25000.0,2014,12,31,201412,105.17,99.298,84374.0,-8.9,363592.748,572664.602,525514.506,1099.2,3.5,2.34
14237683,20141231,대전,배,도매,중품,27000.0,2014,12,31,201412,105.17,99.298,84374.0,-8.9,363592.748,572664.602,525514.506,1099.2,3.5,2.34

In [101]:
df_market["Product"].nunique()

23

In [102]:
set(crop_list) - set(df_market["Product"])

set()

In [196]:
file = f"{data_path}/생산자물가지수_품목별_연도별_월별.xlsx"
df2 = pd.read_excel(file, engine="openpyxl")
# df2 = df2.rename(columns={'계정코드별':'Product'})
# df2["Product"] = df2["Product"].map(lambda x : x.split()[0])
# df2 = df2.replace("-", np.NaN)
# df2 = df2.dropna(axis=0)
# df2 = df2[df2["Product"].isin(crop_list)]
# for i in df2["Product"]:
#     df2["Product"] = df2["Product"].replace(i,f"생산자물가지수_{i}")

# for i in df2.columns:
#     df2.columns = df2.columns.map(lambda x: x.replace(".",""))
    
# df2.stack()

df2

,계정코드별,2005.01,2005.02,2005.03,2005.04,2005.05,2005.06,2005.07,2005.08,2005.09,...,2022.02,2022.03,2022.04,2022.05,2022.06,2022.07,2022.08,2022.09,2022.10,2022.11
0,쌀 (2015=100),101.54,102.03,102.34,102.24,102.34,102.43,102.43,102.03,98.28,...,127.81,125.83,121.04,117.76,115.19,112.30,107.45,103.12,118.95,118.39
1,보리쌀 (2015=100),58.37,58.37,58.37,58.37,58.37,58.37,58.37,58.37,58.37,...,69.32,69.32,69.32,69.32,72.15,76.28,76.28,76.28,76.28,76.28
2,콩 (2015=100),113.85,116.71,124.75,125.41,123.54,118.36,115.07,110.21,105.15,...,147.85,148.00,147.78,150.50,151.84,151.53,151.53,151.53,152.97,147.21
3,감자 (2015=100),71.15,81.05,84.32,93.61,83.21,43.65,29.87,39.66,37.56,...,137.91,151.95,220.30,197.62,131.95,131.27,142.17,142.83,140.36,150.93
4,고구마 (2015=100),53.12,56.55,58.77,67.39,68.48,68.48,68.48,65.73,51.93,...,106.56,102.67,106.02,103.66,104.20,93.86,99.49,94.70,86.18,91.90
5,배추 (2015=100),32.83,42.02,43.85,40.1,37.52,43.65,65.23,74.08,112.14,...,170.18,194.07,216.60,237.59,191.57,281.64,372.02,657.60,252.06,138.34
6,시금치 (2015=100),48.07,62.09,50.1,45.3,45.16,51.59,61.75,61.75,135.95,...,152.30,118.20,96.31,107.70,132.55,402.91,531.36,337.04,123.26,69.37
7,상추 (2015=100),38.65,37.75,40.94,42.96,34.35,30.12,103.81,124.35,120.81,...,79.72,77.45,90.34,80.79,133.85,330.06,298.40,169.75,94.79,59.05
8,부추 (2015=100),-,-,-,-,-,-,-,-,-,...,168.69,158.35,144.07,85.82,73.01,135.51,169.85,138.23,156.79,179.70
9,수박 (2015=100),46.3,46.3,46.3,46.3,46.3,40.1,34.53,34.81,35.66,...,139.76,143.50,147.74,176.95,142.61,191.15,205.62,140.60,122.22,129.74
10,참외 (2015=100),57.57,57.57,57.57,145.31,90.03,55.4,51.65,39.09,37.51,...,111.05,245.72,242.94,137.52,109.11,125.28,141.47,141.47,141.47,141.47
11,오이 (2015=100),115.9,137.26,108.7,67.88,51.66,42.06,50.83,67.47,53.81,...,146.08,144.49,88.49,67.95,87.00,174.41,181.06,147.16,108.19,93.82
12,호박 (2015=100),86.88,93.54,88.17,57.13,34.76,28.38,46.24,98.21,74.26,...,129.30,129.82,84.51,68.90,103.74,147.87,210.90,152.01,108.84,77.14
13,토마토 (2015=100),99.23,108.47,148.5,149.28,101,58.03,75.34,89.29,83.4,...,161.18,180.85,140.62,122.33,116.51,144.23,176.07,209.17,215.21,151.71
14,딸기 (2015=100),145.29,132.26,142.43,127.56,86.54,84,84,84,84,...,154.55,112.59,89.58,76.19,76.19,76.19,76.19,76.19,76.19,76.19
15,파프리카 (2015=100),-,-,-,-,-,-,-,-,-,...,188.49,145.17,116.87,119.39,78.50,92.63,216.38,273.49,151.76,80.88
16,무 (2015=100),35.49,35.49,50.79,55.29,56.08,59.07,96.29,89.74,129.33,...,123.50,121.14,122.95,161.63,181.35,227.61,276.95,369.70,316.00,164.89
17,풋고추 (2015=100),76.99,115.65,122.01,85.71,59.21,47.11,50.16,40.09,53.68,...,188.70,150.71,119.70,127.20,145.16,204.03,147.23,196.88,147.28,116.07
18,건고추 (2015=100),73.23,73.64,74.88,73.36,72.12,71.71,68.68,64.46,64.11,...,150.36,150.22,150.23,149.93,149.62,150.68,151.49,173.86,171.23,166.11
19,마늘 (2015=100),49.58,49.45,48.52,47.58,47.41,43.13,42.57,42.89,43.69,...,147.11,148.61,153.29,153.35,153.90,156.54,158.40,152.41,149.10,148.84
20,파 (2015=100),25.64,33.79,31.7,24.83,30.02,49.89,51.88,61.62,68.96,...,81.75,94.23,73.40,87.67,97.38,118.86,131.86,123.31,119.87,119.92
21,양파 (2015=100),58.59,75.88,83.94,71.83,46.94,35.91,33.3,39.92,39.97,...,58.54,55.24,59.40,74.15,136.45,144.67,148.76,146.77,149.89,149.63
22,생강 (2017.12=100),-,-,-,-,-,-,-,-,-,...,70.20,72.08,69.61,69.20,69.31,69.47,72.35,100.54,134.71,176.02
23,버섯 (2015=100),108.31,108.73,109.14,95.72,88.13,93.87,106.27,111.18,118.36,...,94.81,93.70,105.87,120.22,115.22,111.89,118.60,117.15,108.48,105.41
24,피망 (2015=100),63.5,89.41,113.47,56.8,42.06,43.97,57.43,45.11,96.24,...,197.09,150.74,158.53,130.24,104.54,111.30,119.04,201.85,83.12,91.90
25,사과 (2015=100),128.34,136.47,143.4,156.62,157.82,157.82,157.82,157.82,157.82,...,75.97,61.96,68.09,62.82,79.63,91.67,92.13,92.13,64.92,60.05
26,배 (2015=100),95.79,97.61,109.35,109.45,109.45,109.45,109.45,109.45,89.68,...,133.21,131.25,138.82,149.24,177.62,190.69,176.92,115.06,95.14,98.24
27,복숭아 (2015=100),-,-,-,-,-,-,-,-,-,...,134.04,134.04,134.04,134.04,134.04,158.62,132.19,132.19,132.19,132.19
28,포도 (2015=100),-,-,-,-,-,-,-,-,-,...,137.28,137.28,137.28,137.28,137.28,179.22,176.76,151.56,138.06,143.69
29,감귤 (2015=100),124.88,142.8,152.12,150.83,150.83,150.83,150.83,150.83,150.83,...,80.68,80.68,80.67,80.67,80.67,80.67,80.67,80.67,92.06,76.93
30,감 (2015=100),157.62,189.74,196.78,196.78,196.78,196.78,196.78,196.78,196.78,...,254.89,294.87,294.87,294.87,294.87,294.87,294.87,294.87,177.86,159.79
31,절화류 (2015=100),77.93,89.8,72.01,56.12,55.83,32.02,39.99,42.11,43.07,...,129.29,116.14,107.12,118.29,97.56,96.45,119.27,148.19,132.62,104.08
32,분화류 (2015=100),-,-,-,-,-,-,-,-,-,...,127.02,124.54,147.09,128.31,128.41,130.90,132.69,139.02,109.09,112.41
33,인삼 (2015=100),109.9,124.16,132.5,137.64,140.98,148.68,141.88,140.98,129.94,...,87.77,84.44,87.63,89.77,90.63,92.94,90.33,96.74,80.31,76.68
34,한약재료 (2015=100),47.22,48.71,49.87,53.19,55.29,55.61,55.61,58.1,60.64,...,90.19,89.01,86.52,86.87,87.15,87.21,87.21,87.55,87.84,87.87
35,잎담배 (2015=100),67.06,67.06,75.1,75.1,75.1,75.1,75.1,75.1,75.1,...,108.77,108.77,108.77,108.77,108.77,108.77,108.77,108.77,108.77,108.77
36,참깨 (2015=100),75.25,76.91,82.29,82.22,81.84,81.62,80.93,79.57,67.9,...,151.13,151.86,152.93,154.65,154.37,153.99,150.66,143.56,140.64,137.10
37,들깨 (2015=100),57.39,59.02,60.24,60.07,59.66,58.73,58.32,56.82,52.76,...,156.62,155.37,154.28,154.14,153.86,153.86,153.86,152.96,152.21,150.42
38,생우유 (2015=100),66.84,66.9,66.5,66.3,65.78,65.32,64.59,64.14,64.01,...,102.49,102.49,101.95,101.59,101.00,99.94,99.89,101.44,105.00,107.75

In [209]:
df3 = pd.read_csv(f"{data_path}/소비자물가지수_품목별_연도별_월별_filtered.csv")
df3 = df3.replace("-", np.NaN)
# df3 = df3.rename(columns={'품목별':'YM'}).set_index("YM", drop=True)
# df3 = df3.dropna(axis="rows")ㅋㅋㅋㅋㅋ짜증나게하지마세ㅕㅇ 
# # df3 = df3.drop(index=[0,1,2,10,38])
# # df3["YM"] = df3["YM"].map(lambda x: x.strip())
# # df3 = df3[df3["YM"].isin(crop_list)]
# # for i in df3["YM"]:
# #     df3["YM"] = df3["YM"].replace(i,f"소비자물가지수_{i}")

# for i in df3.columns:
#     df3.columns = df3.columns.map(lambda x: x.replace(".",""))
        
# pd.DataFrame(df3.stack()) 
df3

,품목별,2005.01,2005.02,2005.03,2005.04,2005.05,2005.06,2005.07,2005.08,2005.09,...,2022.02,2022.03,2022.04,2022.05,2022.06,2022.07,2022.08,2022.09,2022.10,2022.11
0,총지수,73.594,73.892,74.338,74.413,74.338,74.114,74.413,74.636,75.008,...,105.30,106.06,106.85,107.56,108.22,108.74,108.62,108.93,109.21,109.10
1,농축수산물,62.157,64.050,64.302,64.681,63.482,61.526,62.788,63.293,65.249,...,111.72,109.89,110.42,112.45,111.80,114.40,116.74,118.99,114.68,109.78
2,(농산물)곡물,76.091,76.015,75.866,75.641,76.015,76.015,75.866,75.716,75.042,...,103.59,102.59,101.13,99.72,98.51,97.32,95.47,93.93,94.40,97.81
3,쌀,75.464,75.539,75.391,75.093,75.242,75.316,75.168,75.019,74.277,...,102.87,101.90,99.94,98.23,96.77,95.23,92.80,90.34,91.08,96.16
4,현미,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,106.62,105.34,105.25,104.03,102.93,102.33,101.34,101.72,101.01,100.42
5,찹쌀,78.245,76.985,76.120,77.694,81.236,81.394,80.212,80.921,80.764,...,103.63,101.56,100.81,99.76,98.74,97.55,95.74,97.04,96.87,95.84
6,보리쌀,61.778,61.839,61.778,61.839,61.901,61.901,61.839,61.716,61.654,...,101.50,102.44,103.10,102.99,103.55,106.59,108.89,109.55,110.14,111.09
7,콩,68.828,68.560,68.022,68.090,67.755,67.217,67.486,67.149,66.880,...,107.30,106.71,105.04,104.34,103.63,103.04,103.01,102.52,102.75,102.03
8,땅콩,53.740,53.166,52.225,52.172,53.061,52.225,53.532,52.800,52.905,...,105.40,105.95,106.17,107.06,106.73,107.11,106.28,106.40,106.03,106.44
9,혼식곡,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,104.67,103.52,104.74,104.34,104.35,103.82,103.72,104.20,104.08,105.56
10,(농산물)채소,50.021,54.884,55.216,53.447,48.749,44.328,51.291,57.206,65.331,...,109.54,104.37,102.60,98.63,96.97,113.61,126.83,138.67,120.57,104.11
11,배추,24.198,30.398,33.948,38.747,34.098,30.548,46.397,59.345,88.144,...,88.07,89.52,99.28,97.11,93.53,121.93,159.40,210.79,145.04,78.42
12,상추,45.498,46.789,45.229,43.294,42.003,38.023,62.708,68.947,69.699,...,101.21,86.35,91.21,85.71,87.19,181.39,179.79,172.65,103.27,88.20
13,시금치,35.507,40.340,34.949,31.231,31.185,31.092,59.488,85.886,76.869,...,108.70,97.84,85.38,90.61,102.30,199.93,263.91,259.07,129.06,94.44
14,양배추,28.861,31.917,30.756,30.215,35.863,33.735,31.608,40.622,47.237,...,69.32,78.05,91.84,107.51,86.90,91.61,95.59,97.27,102.72,95.85
15,미나리,42.061,45.730,41.114,37.760,28.686,24.306,31.921,38.786,46.480,...,150.77,125.38,107.91,96.93,93.65,117.77,138.90,162.98,138.37,135.50
16,깻잎,53.348,56.294,50.309,42.828,39.602,35.908,44.090,44.417,48.953,...,127.90,108.14,109.04,104.66,101.58,111.87,123.33,149.95,123.21,101.30
17,부추,69.016,73.241,63.103,51.062,35.644,28.726,36.277,39.129,36.435,...,154.16,128.50,118.36,89.29,74.66,102.37,118.06,127.79,108.91,128.21
18,무,35.327,40.205,40.675,43.791,44.202,39.911,58.427,70.535,90.755,...,77.93,73.48,71.57,87.46,98.21,122.47,146.13,171.60,174.99,114.19
19,열무,47.582,47.582,70.946,56.072,49.623,48.109,77.067,81.278,82.594,...,118.18,152.02,143.96,106.42,100.72,167.01,181.51,156.32,109.49,94.45
20,당근,54.593,52.496,50.497,50.147,51.446,48.100,47.000,48.899,50.697,...,68.34,66.77,73.34,83.89,82.03,86.07,92.47,112.48,118.10,106.29
21,감자,69.162,74.989,70.888,66.735,66.195,52.277,37.710,37.926,40.246,...,127.38,135.67,156.24,154.11,126.55,114.86,114.35,116.86,116.26,118.13
22,고구마,41.811,43.180,43.843,45.344,46.094,46.094,56.470,47.066,43.180,...,86.90,85.52,84.40,83.65,83.26,83.32,87.10,87.81,83.75,81.28
23,도라지,61.480,61.914,61.789,62.099,61.604,62.038,61.728,61.728,62.533,...,112.73,114.49,115.53,115.95,116.73,116.01,116.58,117.39,118.23,117.41
24,콩나물,64.265,64.585,64.201,63.880,64.137,64.009,64.009,63.816,63.816,...,107.04,109.51,110.38,109.86,110.70,110.37,109.68,108.99,109.47,111.60
25,버섯,94.762,97.888,95.445,95.641,94.274,93.101,96.716,99.548,106.876,...,126.91,115.81,112.45,115.00,114.03,110.53,112.48,126.58,112.91,110.69
26,오이,51.792,64.107,53.364,43.430,38.819,33.802,44.039,48.042,47.586,...,149.86,127.01,116.55,87.01,85.90,148.97,157.40,139.27,124.60,94.26
27,풋고추,57.365,73.732,81.833,62.205,50.514,44.587,43.554,40.618,50.949,...,119.88,114.39,108.12,96.25,97.58,122.52,118.30,133.75,104.78,103.57
28,호박,79.112,95.253,79.182,60.547,42.743,38.239,50.363,76.272,80.705,...,131.18,112.78,95.83,71.25,79.13,119.17,139.60,150.09,101.54,81.50
29,가지,53.620,53.620,53.620,82.555,71.041,59.230,56.159,49.368,53.679,...,136.06,122.55,117.86,100.89,98.59,105.17,110.91,116.72,101.80,98.43
30,토마토,60.050,61.084,67.634,69.991,60.050,44.190,43.098,52.349,59.015,...,116.61,110.45,104.32,87.42,76.49,76.11,102.42,117.71,131.39,112.24
31,파,38.565,40.789,39.487,35.691,34.172,47.678,50.933,60.154,73.659,...,92.63,97.37,83.78,86.96,100.68,108.80,122.35,126.16,115.71,112.33
32,양파,55.449,62.842,72.111,78.677,59.918,48.884,44.690,44.690,48.056,...,83.54,77.04,78.58,78.15,88.41,97.90,101.09,105.93,109.17,111.70
33,마늘,58.270,58.270,59.076,59.479,58.730,57.347,56.194,56.309,56.367,...,139.28,139.48,141.69,144.56,144.86,146.50,146.55,144.96,144.46,142.63
34,브로콜리,70.673,73.381,64.267,65.852,63.804,54.360,59.709,72.193,89.630,...,100.43,89.17,96.52,104.73,87.19,95.17,114.27,138.51,123.66,105.77
35,고사리,68.100,68.374,68.579,68.305,68.168,68.168,67.894,68.579,68.990,...,118.23,119.50,120.31,119.93,120.09,119.89,119.49,122.36,122.85,122.18
36,파프리카,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,128.46,111.67,98.32,98.01,81.39,77.12,110.39,155.60,133.40,95.17
37,생강,47.425,49.972,51.460,52.325,52.277,52.325,52.134,52.277,51.749,...,61.02,61.67,61.95,62.02,62.07,63.67,64.74,68.26,73.11,82.07
38,(농산물)과실,75.370,81.287,83.000,88.528,85.647,79.730,80.041,77.627,77.862,...,119.53,119.25,121.04,119.11,118.06,120.78,123.50,118.15,115.84,106.83
39,사과,79.064,93.523,96.489,100.474,101.401,101.401,101.401,101.401,101.401,...,102.88,102.08,99.87,100.67,105.48,112.07,117.77,105.89,95.20,92.91
40,배,68.187,73.784,76.547,77.564,77.564,77.564,77.564,77.564,82.217,...,119.20,120.04,117.85,119.97,124.98,128.98,124.17,118.03,104.94,96.69
41,복숭아,89.542,89.542,89.542,89.542,89.542,89.542,90.508,87.169,84.973,...,139.27,135.25,137.69,133.56,129.78,137.17,127.86,136.40,130.99,121.20
42,포도,107.898,107.898,107.898,107.898,107.898,107.898,143.963,88.974,75.896,...,126.67,122.50,122.89,128.01,133.53,154.93,158.97,138.43,131.76,121.98
43,밤,70.421,70.759,70.083,70.083,70.083,70.083,70.083,72.247,63.859,...,99.38,99.14,100.02,99.37,99.84,99.88,98.85,97.21,99.11,98.31
44,감,65.976,82.984,94.238,99.736,99.736,99.736,99.736,99.736,99.736,...,130.03,131.36,130.58,130.62,130.26,130.73,130.16,130.37,114.48,96.96
45,귤,60.660,76.945,82.193,83.505,83.505,83.505,83.505,83.505,83.505,...,110.99,129.07,131.45,127.51,124.05,124.37,127.32,122.19,142.15,113.06
46,오렌지,88.103,88.621,87.068,95.438,96.128,81.372,78.524,80.338,83.530,...,130.30,125.41,125.39,127.20,126.44,126.80,129.69,124.65,119.74,110.71
47,참외,89.936,89.936,89.936,161.234,126.035,82.373,69.229,74.180,74.360,...,107.75,153.77,177.16,139.86,109.45,98.69,111.70,108.58,105.11,97.89
48,수박,87.153,87.153,87.153,87.153,83.600,60.108,51.189,61.196,66.344,...,138.24,134.21,136.65,141.53,130.73,128.08,142.38,136.83,131.49,121.57
49,딸기,89.212,84.847,79.316,78.538,72.850,72.148,72.148,72.148,72.148,...,151.98,104.64,99.91,98.40,95.58,95.86,98.11,94.39,90.70,83.87
50,바나나,55.297,59.839,61.371,62.620,58.817,59.328,54.331,54.218,57.795,...,106.32,110.37,117.21,122.47,121.65,116.57,114.02,112.11,115.58,115.45
51,키위,99.036,99.036,99.229,99.132,104.838,103.194,93.716,96.037,94.296,...,115.04,117.00,120.21,121.30,119.20,120.09,119.46,121.91,119.24,118.81

In [181]:
# 이게 우신님꺼
df_eco = pd.concat([df2, df3], axis = 0).set_index("YM").T
df_eco

YM,생산자물가지수_쌀,생산자물가지수_콩,생산자물가지수_감자,생산자물가지수_고구마,생산자물가지수_배추,생산자물가지수_시금치,생산자물가지수_오이,생산자물가지수_호박,생산자물가지수_무,생산자물가지수_풋고추,...,소비자물가지수_오이,소비자물가지수_풋고추,소비자물가지수_호박,소비자물가지수_양파,소비자물가지수_마늘,소비자물가지수_생강,소비자물가지수_사과,소비자물가지수_배,소비자물가지수_복숭아,소비자물가지수_포도
200501,101.54,113.85,71.15,53.12,32.83,48.07,115.9,86.88,35.49,76.99,...,51.792,57.365,79.112,55.449,58.270,47.425,79.064,68.187,89.542,107.898
200502,102.03,116.71,81.05,56.55,42.02,62.09,137.26,93.54,35.49,115.65,...,64.107,73.732,95.253,62.842,58.270,49.972,93.523,73.784,89.542,107.898
200503,102.34,124.75,84.32,58.77,43.85,50.1,108.7,88.17,50.79,122.01,...,53.364,81.833,79.182,72.111,59.076,51.460,96.489,76.547,89.542,107.898
200504,102.24,125.41,93.61,67.39,40.1,45.3,67.88,57.13,55.29,85.71,...,43.430,62.205,60.547,78.677,59.479,52.325,100.474,77.564,89.542,107.898
200505,102.34,123.54,83.21,68.48,37.52,45.16,51.66,34.76,56.08,59.21,...,38.819,50.514,42.743,59.918,58.730,52.277,101.401,77.564,89.542,107.898
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202207,112.3,151.53,131.27,93.86,281.64,402.91,174.41,147.87,227.61,204.03,...,148.97,122.52,119.17,97.9,146.5,63.67,112.07,128.98,137.17,154.93
202208,107.45,151.53,142.17,99.49,372.02,531.36,181.06,210.9,276.95,147.23,...,157.4,118.3,139.6,101.09,146.55,64.74,117.77,124.17,127.86,158.97
202209,103.12,151.53,142.83,94.7,657.6,337.04,147.16,152.01,369.7,196.88,...,139.27,133.75,150.09,105.93,144.96,68.26,105.89,118.03,136.4,138.43
202210,118.95,152.97,140.36,86.18,252.06,123.26,108.19,108.84,316.0,147.28,...,124.6,104.78,101.54,109.17,144.46,73.11,95.2,104.94,130.99,131.76
202211,118.39,147.21,150.93,91.9,138.34,69.37,93.82,77.14,164.89,116.07,...,94.26,103.57,81.5,111.7,142.63,82.07,92.91,96.69,121.2,121.98

In [157]:
df_eco["YM"]

KeyError: 'YM'

In [156]:
pd.merge(df_market, df_eco, on="YM")

KeyError: 'YM'